version: '3.8'
services:
    postgres:
        container_name: 'postgres-db'
        image: postgres:12-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=avito
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - '5432:5432'
        volumes:
            - db-data:/var/lib/postgresql/data

    redis:
        container_name: 'redis-queue'
        image: redis:7-alpine
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
    back:
        container_name: 'back'
        build: .
        depends_on:
            - postgres
            - redis
        ports:
            - 8000:8000
        volumes:
            - ./configs:/opt/app/configs

volumes:
    db-data:
    redis_data: